# Generated by Django 3.1 on 2024-06-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/partners'),
        ),
        migrations.AddField(
            model_name='value',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/partners'),
        ),
    ]
