# Generated by Django 5.0.6 on 2024-09-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0005_alter_document_id_alter_documentcategory_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program",
            options={"ordering": ["ordering_number", "title"]},
        ),
        migrations.AddField(
            model_name="program",
            name="ordering_number",
            field=models.IntegerField(default=0),
        ),
    ]
