# Generated by Django 5.0.6 on 2024-12-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0006_alter_program_options_program_ordering_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="partners",
            name="ordering_number",
            field=models.IntegerField(default=0),
        ),
    ]
