# Generated by Django 5.0.6 on 2024-12-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0007_partners_ordering_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img/partners"),
        ),
    ]
