# Generated by Django 5.0.6 on 2025-02-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0008_program_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="subtitle_en",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="title_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="documentcategory",
            name="name_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="history",
            name="content_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="history",
            name="title_en",
            field=models.CharField(default="History of Unite Together", max_length=255),
        ),
        migrations.AddField(
            model_name="mission",
            name="content_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="mission",
            name="title_en",
            field=models.CharField(default="Mission", max_length=255),
        ),
        migrations.AddField(
            model_name="partners",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="partners",
            name="title_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="program",
            name="additional_info_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="category_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="program",
            name="description_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="program",
            name="support_partner_en",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="title_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="value",
            name="content_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="value",
            name="title_en",
            field=models.CharField(default="Values", max_length=255),
        ),
        migrations.AddField(
            model_name="vision",
            name="content_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="vision",
            name="title_en",
            field=models.CharField(default="Vision", max_length=255),
        ),
        migrations.AlterField(
            model_name="history",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="mission",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="program",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="value",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="vision",
            name="content",
            field=models.TextField(default=""),
        ),
    ]
