# Generated by Django 5.0.6 on 2025-07-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0009_document_subtitle_en_document_title_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("phone_number", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("geolocation", models.CharField(max_length=255)),
                ("instagram", models.URLField()),
                ("facebook", models.URLField()),
                ("telegram", models.URLField()),
            ],
        ),
    ]
