# Generated by Django 5.0.6 on 2025-07-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0010_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="address_en",
            field=models.CharField(default="", max_length=255),
        ),
    ]
