# Generated by Django 5.0.6 on 2024-06-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="family_identifier",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
