# Generated by Django 5.0.6 on 2024-06-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_account_family_identifier_alter_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="family_identifier",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
