# Generated by Django 5.0.6 on 2024-07-17 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_account_family_identifier"),
        ("persons", "0029_alter_person_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="associated_person",
            field=models.OneToOneField(
                blank="True",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.associatedperson",
            ),
        ),
    ]
