# Generated by Django 5.0.6 on 2024-09-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_account_associated_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_supervisor",
            field=models.BooleanField(default=False),
        ),
    ]
