# Generated by Django 5.0.6 on 2024-06-22 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SectionAboutUs",
            fields=[
                (
                    "section_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="homepage.section",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="img/about_us"),
                ),
            ],
            bases=("homepage.section",),
        ),
        migrations.CreateModel(
            name="SectionEvents",
            fields=[
                (
                    "section_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="homepage.section",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="img/events"),
                ),
            ],
            bases=("homepage.section",),
        ),
        migrations.CreateModel(
            name="SectionProjects",
            fields=[
                (
                    "section_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="homepage.section",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="img/projects"),
                ),
            ],
            bases=("homepage.section",),
        ),
    ]
