# Generated by Django 5.0.6 on 2024-06-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_calltoaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="calltoaction",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img/homepage"),
        ),
    ]
