# Generated by Django 5.0.6 on 2025-02-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_calltoaction_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="calltoaction",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="calltoaction",
            name="title_en",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
