# Generated by Django 5.0.6 on 2025-02-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_calltoaction_description_en_calltoaction_title_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="subtitle_en",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="text_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="title_en",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
