# Generated by Django 3.1 on 2024-05-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0013_projects'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.person')),
                ('registered_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_pages.webcontentobject')),
            ],
            bases=('persons.person',),
        ),
    ]
