# Generated by Django 3.1 on 2024-05-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.person')),
            ],
            bases=('persons.person',),
        ),
    ]
