# Generated by Django 3.1 on 2024-05-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_associatedperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user_owner',
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=3),
        ),
    ]
