# Generated by Django 3.1 on 2024-06-03 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20240601_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persons.associatedperson'),
        ),
    ]
