# Generated by Django 3.1 on 2024-06-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20240603_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(blank=True, choices=[('Reg', 'Registered'), ('Csl', 'Canceled'), ('Vst', 'Visited')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='document_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
