# Generated by Django 3.1 on 2024-06-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20240605_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Canceled', 'Canceled'), ('Visited', 'Visited')], max_length=10, null=True),
        ),
    ]
