# Generated by Django 3.1 on 2024-06-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_auto_20240606_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='document_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
