# Generated by Django 3.1 on 2024-06-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_auto_20240606_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='document_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
