# Generated by Django 3.1 on 2024-06-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_auto_20240606_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
