# Generated by Django 3.1 on 2024-06-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0012_auto_20240610_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Canceled', 'Canceled'), ('Visited', 'Visited')], max_length=10, null=True),
        ),
    ]
