# Generated by Django 3.1 on 2024-06-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0021_webcontentsubordinateobject_created_at'),
        ('persons', '0013_auto_20240610_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='region',
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_pages.city'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=7, null=True),
        ),
    ]
