# Generated by Django 3.1 on 2024-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0015_auto_20240610_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
