# Generated by Django 3.1 on 2024-06-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0016_auto_20240610_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
    ]
