# Generated by Django 3.1 on 2024-06-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_remove_person_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='new_city',
        ),
    ]
