# Generated by Django 3.1 on 2024-06-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0021_webcontentsubordinateobject_created_at'),
        ('persons', '0018_remove_person_new_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='chosen_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_pages.city'),
        ),
    ]
