# Generated by Django 3.1 on 2024-06-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0019_person_chosen_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regex', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='edit_permission',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='type_of_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.typeofdocument'),
        ),
    ]
