# Generated by Django 3.1 on 2024-06-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0020_auto_20240611_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofdocument',
            name='hint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
