# Generated by Django 3.1 on 2024-06-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0023_create_document_types_with_hint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='type_of_document',
        ),
    ]
