# Generated by Django 3.1 on 2024-06-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0025_auto_20240611_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
    ]
