# Generated by Django 5.0.6 on 2024-06-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0027_alter_person_id_alter_typeofdocument_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="associatedperson",
            name="unique_identifier",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="copy_of_unique_identifier",
            field=models.CharField(
                blank=True, editable=False, max_length=15, null=True
            ),
        ),
    ]
