# Generated by Django 5.0.6 on 2024-07-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0028_associatedperson_unique_identifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=3,
                null=True,
            ),
        ),
    ]
