# Generated by Django 5.0.6 on 2024-08-01 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0029_alter_person_gender"),
        ("web_pages", "0026_events_max_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="registered_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_pages.events",
            ),
        ),
    ]
