# Generated by Django 5.0.6 on 2024-08-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0030_alter_participant_registered_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="citizenship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Georgian", "Georgian"),
                    ("Ukrainian", "Ukrainian"),
                    ("Other", "Other"),
                ],
                default="Georgian",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="country",
            field=models.CharField(
                blank=True, choices=[("Georgia", "Georgia")], max_length=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=6,
                null=True,
            ),
        ),
    ]
