# Generated by Django 5.0.6 on 2024-08-27 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0031_alter_person_citizenship_alter_person_country_and_more"),
        ("web_pages", "0026_events_max_participants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="criteria",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "A",
                        "Тяжко хворі, з інвалідністю чи обмеженими можливостями (з наявними в документами)",
                    ),
                    ("B", "Старше 60 років (за датою народження)"),
                    ("C", "Багатодітна родина (3 та більше дитини до 18 років)"),
                    (
                        "D",
                        "Одинока мати/ батько, що самостійно виховує неповнолітніх дітей",
                    ),
                    ("E", "Жоден з вищеперечислених критеріїв не підходить"),
                ],
                max_length=1,
                null=True,
                verbose_name="Критерій",
            ),
        ),
        migrations.AlterField(
            model_name="associatedperson",
            name="unique_identifier",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="Унікальний ідентифікатор",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="copy_of_unique_identifier",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=15,
                null=True,
                verbose_name="Копія унікального ідентифікатора",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="registered_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_pages.events",
                verbose_name="Зареєстровано на",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Зареєстрований", "Зареєстрований"),
                    ("Скасовано", "Скасовано"),
                    ("Відвідали", "Відвідали"),
                ],
                max_length=14,
                null=True,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="address_line",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Адреса"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="chosen_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_pages.city",
                verbose_name="Вибране місто",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="citizenship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Грузинське", "Грузинське"),
                    ("Українське", "Українське"),
                    ("Інше", "Інше"),
                ],
                default="Грузинське",
                max_length=20,
                null=True,
                verbose_name="Громадянство",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[("Грузія", "Грузія")],
                default="Грузія",
                max_length=7,
                null=True,
                verbose_name="Країна",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата створення"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_arrival",
            field=models.DateField(blank=True, null=True, verbose_name="Дата прибуття"),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата народження"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="document_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер документа"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="edit_permission",
            field=models.BooleanField(
                default=True, verbose_name="Дозвіл на редагування"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ім'я"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Чоловік", "Чоловік"), ("Жінка", "Жінка"), ("Інше", "Інше")],
                max_length=7,
                null=True,
                verbose_name="Стать",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="georgian_phone_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Грузинський номер телефону",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активний"),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Схвалено"),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Прізвище"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="type_of_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.typeofdocument",
                verbose_name="Тип документа",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="ukrainian_phone_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Український номер телефону",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
        ),
        migrations.AlterField(
            model_name="person",
            name="user_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Власник акаунту",
            ),
        ),
        migrations.AlterField(
            model_name="typeofdocument",
            name="hint",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Підказка"
            ),
        ),
        migrations.AlterField(
            model_name="typeofdocument",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="typeofdocument",
            name="regex",
            field=models.CharField(max_length=100, verbose_name="Регулярний вираз"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.associatedperson",
                verbose_name="Пов'язана особа",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
    ]
