# Generated by Django 5.0.6 on 2024-09-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0032_person_criteria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="criteria",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "A",
                        "A - Тяжко хворі, з інвалідністю чи обмеженими можливостями (з наявними в документами)",
                    ),
                    ("B", "B - Старше 60 років (за датою народження)"),
                    ("C", "C - Багатодітна родина (3 та більше дитини до 18 років)"),
                    (
                        "D",
                        "D - Одинока мати/ батько, що самостійно виховує неповнолітніх дітей",
                    ),
                    ("E", "E - Жоден з вищеперечислених критеріїв не підходить"),
                ],
                default="E",
                max_length=1,
                null=True,
                verbose_name="Критерій",
            ),
        ),
    ]
