# Generated by Django 5.0.6 on 2025-07-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0034_alter_person_user_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ім'я (Латиниця)"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Чоловік", "Чоловік"), ("Жінка", "Жінка")],
                max_length=7,
                null=True,
                verbose_name="Стать",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Прізвище (Латиниця)"
            ),
        ),
    ]
