# Generated by Django 5.0.3 on 2024-03-22 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebContentSubordinateObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("title", models.CharField(max_length=250)),
                ("text", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="img/pages_content_sub"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_pages.webcontentobject",
                    ),
                ),
            ],
        ),
    ]
