# Generated by Django 5.0.3 on 2024-03-22 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "web_pages",
            "0003_rename_content_webcontentsubordinateobject_content_master_object",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webcontentobject",
            name="subordinate_objects",
        ),
        migrations.AddField(
            model_name="webcontentobject",
            name="web_page_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_pages.webpage",
            ),
        ),
        migrations.DeleteModel(
            name="WebPageSection",
        ),
    ]
