# Generated by Django 5.0.3 on 2024-03-22 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0005_alter_webcontentobject_web_page_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webcontentobject",
            name="web_page_owner",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_pages.webpage",
            ),
        ),
    ]
