# Generated by Django 5.0.3 on 2024-04-08 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0006_alter_webcontentobject_web_page_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "webcontentobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web_pages.webcontentobject",
                    ),
                ),
                ("city", models.CharField(max_length=250)),
                ("age", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            bases=("web_pages.webcontentobject",),
        ),
        migrations.RemoveField(
            model_name="webcontentobject",
            name="web_page_owner",
        ),
        migrations.AddField(
            model_name="webcontentobject",
            name="slug",
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="ObjectsGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_pages.webpage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="webcontentobject",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_pages.objectsgroup",
            ),
        ),
    ]
