# Generated by Django 5.0.3 on 2024-04-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0007_events_remove_webcontentobject_web_page_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectsgroup",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
