# Generated by Django 5.0.3 on 2024-04-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0008_objectsgroup_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="age",
        ),
        migrations.AddField(
            model_name="events",
            name="end_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="start_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="events",
            name="city",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="events",
            name="end_date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="events",
            name="start_date",
            field=models.DateField(blank=True),
        ),
    ]
