# Generated by Django 3.1 on 2024-04-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0010_auto_20240417_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
