# Generated by Django 3.1 on 2024-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0014_projectgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='extra_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
