# Generated by Django 3.1 on 2024-06-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0015_projects_extra_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectsgroup',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='objectsgroup',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
