# Generated by Django 3.1 on 2024-06-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0016_auto_20240603_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='url_linc',
            field=models.URLField(blank=True, null=True),
        ),
    ]
