# Generated by Django 3.1 on 2024-06-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0017_projects_url_linc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='url_linc',
            new_name='url_link',
        ),
    ]
