# Generated by Django 3.1 on 2024-06-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0018_auto_20240604_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcontentobject',
            name='status',
            field=models.CharField(blank=True, choices=[('Reg', 'Registered'), ('Csl', 'Canceled'), ('Vst', 'Visited')], max_length=3, null=True),
        ),
    ]
