# Generated by Django 3.1 on 2024-06-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0019_webcontentobject_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='extra_details',
        ),
        migrations.RemoveField(
            model_name='webcontentobject',
            name='status',
        ),
        migrations.AddField(
            model_name='webcontentobject',
            name='extra_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
