# Generated by Django 3.1 on 2024-06-06 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0020_auto_20240605_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcontentsubordinateobject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
