# Generated by Django 5.0.6 on 2024-06-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0022_alter_city_id_alter_objectsgroup_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Initiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="initiatives/")),
                ("order", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="webcontentobject",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="WebContentSubordinateObject",
        ),
    ]
