# Generated by Django 5.0.6 on 2024-06-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0023_initiative_webcontentobject_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="initiatives/"),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
