# Generated by Django 5.0.6 on 2024-06-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0024_initiative_link_alter_initiative_description_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Initiative",
        ),
        migrations.AddField(
            model_name="webcontentobject",
            name="show_in_main_page_carousel",
            field=models.BooleanField(default=False),
        ),
    ]
