# Generated by Django 5.0.6 on 2024-07-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0025_delete_initiative_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="max_participants",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
