# Generated by Django 5.0.6 on 2024-11-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0026_events_max_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="webcontentobject",
            name="selected_cities_list",
            field=models.ManyToManyField(
                blank=True, related_name="web_content_objects", to="web_pages.city"
            ),
        ),
    ]
