# Generated by Django 5.0.6 on 2024-12-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0027_webcontentobject_selected_cities_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_us_banner_image", models.ImageField(upload_to="img/banners/")),
                (
                    "about_us_banner_mob_image",
                    models.ImageField(upload_to="img/banners/"),
                ),
                ("about_us_banner_title", models.CharField(max_length=255)),
                ("about_us_banner_text", models.CharField(max_length=255)),
                ("events_banner_image", models.ImageField(upload_to="img/banners/")),
                (
                    "events_banner_mob_image",
                    models.ImageField(upload_to="img/banners/"),
                ),
                ("events_banner_title", models.CharField(max_length=255)),
                ("events_banner_text", models.CharField(max_length=255)),
                ("projects_banner_image", models.ImageField(upload_to="img/banners/")),
                (
                    "projects_banner_mob_image",
                    models.ImageField(upload_to="img/banners/"),
                ),
                ("projects_banner_title", models.CharField(max_length=255)),
                ("projects_banner_text", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Banner Settings",
                "verbose_name_plural": "Banner Settings",
            },
        ),
    ]
