# Generated by Django 5.0.6 on 2024-12-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0028_bannersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="webcontentobject",
            name="extra_details_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="webcontentobject",
            name="text_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="webcontentobject",
            name="title_en",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
    ]
