# Generated by Django 5.0.6 on 2024-12-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0029_webcontentobject_extra_details_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectsgroup",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
    ]
