# Generated by Django 5.0.6 on 2025-01-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0030_objectsgroup_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="webcontentobject",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
