# Generated by Django 5.0.6 on 2025-02-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0031_webcontentobject_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannersettings",
            name="about_us_banner_text_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bannersettings",
            name="about_us_banner_title_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bannersettings",
            name="events_banner_text_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bannersettings",
            name="events_banner_title_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bannersettings",
            name="projects_banner_text_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bannersettings",
            name="projects_banner_title_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="city",
            name="name_en",
            field=models.CharField(default="", max_length=250),
        ),
    ]
