# Generated by Django 5.0.6 on 2025-03-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pages", "0032_bannersettings_about_us_banner_text_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webcontentobject",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
