# Generated by Django 3.2 on 2025-10-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0033_webcontentobject_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('webcontentobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_pages.webcontentobject')),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('selected_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_pages.city')),
            ],
            bases=('web_pages.webcontentobject',),
        ),
    ]
