# Generated by Django 3.2 on 2025-10-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0034_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='add_to_news_carousel',
            field=models.BooleanField(default=False),
        ),
    ]
