# Generated by Django 3.2 on 2025-10-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0035_news_add_to_news_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/news/')),
                ('news', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web_pages.news')),
            ],
            options={
                'verbose_name': 'newsgallery',
                'verbose_name_plural': 'news galleries',
            },
        ),
    ]
