# Generated by Django 3.2 on 2025-12-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0036_newsgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
